# Generated by Django 2.1.1 on 2018-09-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180926_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
    ]
